### ISSUE TITLE
/info/ endpoint is broken when using uWSGI/nginx stack

### ISSUE THREAD

**Issue by robinuniverse** [robinuniverse/TwitFix#16]
Pretty much all in the title. I suspect it's for a similar reason that long twitter redirects are broken as well, though I still can't say exactly what is causing it

**Comment by robinuniverse** [comment]
[generic] f59PbbHUpDw: Requesting header
WARNING: Could not send HEAD request to https:/youtube.com/shorts/f59PbbHUpDw: <urlopen error no host given>
[generic] f59PbbHUpDw: Downloading webpage
ERROR: Unable to download webpage: <urlopen error no host given> (caused by URLError('no host given'))
[2021-12-03 01:20:32,555] ERROR in app: Exception on /info/https:/youtube.com/shorts/f59PbbHUpDw [GET]
Traceback (most recent call last):
  File "/home/robin/twitfix/twitfixenv/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 634, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/home/robin/twitfix/twitfixenv/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 2288, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.9/urllib/request.py", line 514, in open
    req = meth(req)
  File "/usr/lib/python3.9/urllib/request.py", line 1270, in do_request_
    raise URLError('no host given')
urllib.error.URLError: <urlopen error no host given>
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/robin/twitfix/twitfixenv/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/home/robin/twitfix/twitfixenv/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/home/robin/twitfix/twitfixenv/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/home/robin/twitfix/twitfixenv/lib/python3.9/site-packages/youtube_dl/extractor/generic.py", line 2427, in _real_extract
    full_response = self._request_webpage(request, video_id)
  File "/home/robin/twitfix/twitfixenv/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 652, in _request_webpage
    raise ExtractorError(errmsg, sys.exc_info()[2], cause=err)
youtube_dl.utils.ExtractorError: Unable to download webpage: <urlopen error no host given> (caused by URLError('no host given'))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/robin/twitfix/twitfixenv/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/robin/twitfix/twitfixenv/lib/python3.9/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/robin/twitfix/twitfixenv/lib/python3.9/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/robin/twitfix/twitfixenv/lib/python3.9/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/robin/twitfix/./twitfix.py", line 103, in info
    result = ydl.extract_info(sub_path, download=False)
  File "/home/robin/twitfix/twitfixenv/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 808, in extract_info
    return self.__extract_info(url, ie, download, extra_info, process)
  File "/home/robin/twitfix/twitfixenv/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 824, in wrapper
    self.report_error(compat_str(e), e.format_traceback())
  File "/home/robin/twitfix/twitfixenv/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 628, in report_error
    self.trouble(error_message, tb)
  File "/home/robin/twitfix/twitfixenv/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 598, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: Unable to download webpage: <urlopen error no host given> (caused by URLError('no host given'))
